// <auto-generated />
using System;
using Centric_Payment_API.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Centric_Payment_API.Migrations
{
    [DbContext(typeof(PaymentEntities))]
    partial class PaymentEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Centric_Payment_API.DataBase.HistoricalPayments", b =>
                {
                    b.Property<decimal?>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesforceBillingAccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.ToTable("paymentHistory");
                });

            modelBuilder.Entity("Centric_Payment_API.DataBase.PaymentHistoryRecord", b =>
                {
                    b.Property<int?>("recorded_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("recorded_id"), 1L, 1);

                    b.Property<string>("client_receipt_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("old_acct_id")
                        .HasColumnType("int");

                    b.Property<string>("salesforce_acct_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("statement_no")
                        .HasColumnType("int");

                    b.Property<int?>("transaction_amount")
                        .HasColumnType("int");

                    b.Property<int?>("transaction_applied_amount")
                        .HasColumnType("int");

                    b.Property<string>("transaction_comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transaction_create_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transaction_currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transaction_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("transaction_id")
                        .HasColumnType("int");

                    b.Property<string>("transaction_ref_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("transaction_source_id")
                        .HasColumnType("int");

                    b.Property<int?>("transaction_type")
                        .HasColumnType("int");

                    b.HasKey("recorded_id");

                    b.ToTable("PaymentHistoryRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
