// <auto-generated />
using System;
using Centric_Payment_API.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Centric_Payment_API.Migrations.UsageEntitiesMigrations
{
    [DbContext(typeof(UsageEntities))]
    [Migration("20240829062658_UsageMigration")]
    partial class UsageMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Centric_Payment_API.DataBase.HistoricalUsage", b =>
                {
                    b.Property<DateTime?>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("salesforce_billing_account_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("total_amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("unit_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("usage_id")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("historicalUsage");
                });

            modelBuilder.Entity("Centric_Payment_API.DataBase.UsageHistoryRecord", b =>
                {
                    b.Property<int?>("recorded_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("recorded_id"), 1L, 1);

                    b.Property<string>("MIU_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("acct_locale_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("acct_locale_no")
                        .HasColumnType("int");

                    b.Property<int?>("actual_usage")
                        .HasColumnType("int");

                    b.Property<int?>("billable_acct_no")
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_billable_acct_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_master_plan_instance_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_plan_instance_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_record_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date_installed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("end_read")
                        .HasColumnType("int");

                    b.Property<string>("end_read_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("filtered_usage_count")
                        .HasColumnType("int");

                    b.Property<int?>("invoice_no")
                        .HasColumnType("int");

                    b.Property<string>("is_excluded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("location_no")
                        .HasColumnType("int");

                    b.Property<string>("manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("master_plan_instance_no")
                        .HasColumnType("int");

                    b.Property<string>("meter_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("old_acct_id")
                        .HasColumnType("int");

                    b.Property<int?>("plan_instance_id")
                        .HasColumnType("int");

                    b.Property<string>("qualifier_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qualifier_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qualifier_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qualifier_4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("reading_days")
                        .HasColumnType("int");

                    b.Property<int?>("recorded_units")
                        .HasColumnType("int");

                    b.Property<string>("revenue_class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("salesforce_acct_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("start_read")
                        .HasColumnType("int");

                    b.Property<string>("telco_To")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telco_from")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("units")
                        .HasColumnType("int");

                    b.Property<string>("units_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usage_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("usage_record_no")
                        .HasColumnType("int");

                    b.Property<string>("usage_time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usage_type_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usage_type_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("usage_type_no")
                        .HasColumnType("int");

                    b.Property<string>("usage_units_description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("recorded_id");

                    b.ToTable("usageHistory");
                });

            modelBuilder.Entity("Centric_Payment_API.DataBase.UsageHistorySource", b =>
                {
                    b.Property<int?>("MIU_number")
                        .HasColumnType("int");

                    b.Property<int?>("account_no")
                        .HasColumnType("int");

                    b.Property<int?>("actual_usage")
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date_installed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("end_read")
                        .HasColumnType("int");

                    b.Property<string>("end_read_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("location_no")
                        .HasColumnType("int");

                    b.Property<string>("manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("meter_no")
                        .HasColumnType("int");

                    b.Property<int?>("model_no")
                        .HasColumnType("int");

                    b.Property<int?>("reading_days")
                        .HasColumnType("int");

                    b.Property<string>("revenue_class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("start_read")
                        .HasColumnType("int");

                    b.ToTable("usageHistorySource");
                });
#pragma warning restore 612, 618
        }
    }
}
